version: "3.7"
services:
  web-endscom:
    container_name: cn_site_endscom
    image: kooldev/php:7.4-nginx-sqlsrv-prod
    restart: always
    volumes:
      - "./Site:/app"
      - "~/Devs/umk_docker/default.tmpl:/kool/default.tmpl"
    ports:
      - "84:80"
    environment:
      - APP_NAME=endscom
      - PHP_FPM_LISTEN=/run/php-fpm.sock
      - NGINX_LISTEN=80
      - NGINX_ROOT=/app
      - NGINX_INDEX=index.html
      - NGINX_CLIENT_MAX_BODY_SIZE=25M
      - NGINX_PHP_FPM=unix:/run/php-fpm.sock
      - NGINX_FASTCGI_READ_TIMEOUT=60s
      - NGINX_FASTCGI_BUFFERS=8 8k
      - NGINX_FASTCGI_BUFFER_SIZE=16k

  web_marangelo:
    container_name: cn_portafolio_marangelo
    image: kooldev/php:7.4-nginx-sqlsrv-prod
    restart: always
    volumes:
      - "./marangelo/dist:/app"
      - "~/Devs/umk_docker/default.tmpl:/kool/default.tmpl"
    ports:
      - "84:80"
    environment:
      - APP_NAME=wMarangelo
      - PHP_FPM_LISTEN=/run/php-fpm.sock
      - NGINX_LISTEN=80
      - NGINX_ROOT=/app
      - NGINX_INDEX=index.html
      - NGINX_CLIENT_MAX_BODY_SIZE=25M
      - NGINX_PHP_FPM=unix:/run/php-fpm.sock
      - NGINX_FASTCGI_READ_TIMEOUT=60s
      - NGINX_FASTCGI_BUFFERS=8 8k
      - NGINX_FASTCGI_BUFFER_SIZE=16k
